### PR TITLE
browser support and better output

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
It's meant for use with browserify

**Comment by TrySound** [comment]
It would be cool to use instead of known assertion libraries.

**Comment by TrySound** [comment]
I meant much faster just use `<script src="node_modules/...">`

**Comment by calvinmetcalf** [comment]
https://wzrd.in/standalone/minimalistic-assert

**Comment by TrySound** [comment]
Oh, thanks! Do you like new output?

**Comment by TrySound** [comment]
@calvinmetcalf However it still couldn't be added in `<script>`

**Comment by calvinmetcalf** [comment]
you can do `<script src="https://wzrd.in/standalone/minimalistic-assert"></script>` right now and then do `var assert = window['minimalistic-assert'];` inside your local script, this will do what you want and also be compatible with requirejs module systems and will work in a web worker.  

The entire point of this library was to make the smallest possible assert library for use when browserifing packages to avoid unnecessary bloat so the more fully developed errors are something that is not really needed for **this package** but this package is a fairly niche thing made for a fairly specific purpose, if you need an assertion library I highly recommend [chai](http://chaijs.com/).

**Pull request closed without merging**
